name: 'SSH Action'
description: 'Connect to a remote server via SSH and execute commands'
inputs:
  host:
    description: 'Hostname or IP address of the remote server'
    required: true
  port:
    description: 'SSH port of the remote server (default: 22)'
    required: false
    default: '22'
  username:
    description: 'SSH username'
    required: true
  password:
    description: 'SSH password'
    required: true
  command:
    description: 'Commands'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
