name: 'SSH Action'
description: 'Execute SSH commands on a remote server'
inputs:
  host:
    description: 'Remote host'
    required: true
  username:
    description: 'SSH username'
    required: true
  password:
    description: 'SSH password'
    required: true
  command:
    description: 'Command to execute on the remote server'
    required: true
runs:
  using: 'docker'
  image: 'vochilong/ssh-action:latest'
