name: SSH Action
description: Execute SSH commands on a remote server
inputs:
  host:
    description: 'Remote host'
    required: true
  username:
    description: 'SSH username'
    required: true
  ssh_key_path:
    description: 'Path to SSH private key'
    required: true
  command:
    description: 'Command to execute on the remote server'
    required: true
runs:
  using: 'bash'
  main: 'run.sh'
